export enum ChainIdNumber {
  ETHEREUM = 1,
  BSC = 56,
  ARBITRUM = 42161,
  POLYGON = 137,
  OPTIMISM = 10,
  AVALANCHE = 43114,
  BASE = 8453,
  ZKSYNC = 324,
  FANTOM = 250,
  LINEA = 59144,
  SCROLL = 534352,
  MANTLE = 5000,
  BLAST = 81457,
  SONIC = 146,
  BERACHAIN = 80094,
  RONIN = 2020,
}

export enum ChainIdentifier {
  ETHEREUM = 'ethereum',
  BSC = 'bsc',
  ARBITRUM = 'arbitrum',
  POLYGON = 'polygon',
  OPTIMISM = 'optimism',
  AVALANCHE = 'avalanche',
  BASE = 'base',
  ZKSYNC = 'zksync',
  FANTOM = 'fantom',
  LINEA = 'linea',
  SCROLL = 'scroll',
  MANTLE = 'mantle',
  BLAST = 'blast',
  SONIC = 'sonic',
  BERACHAIN = 'berachain',
  RONIN = 'ronin',
} 